version: "3"
services:
  samba:
    build: .
    image: samba-anonymus
    pull_policy: build
    container_name: nas
    ports:
      - "445:445"
    environment:
      - UID=1003
      - GID=1004
    volumes:
      - /mnt/ext-disk:/data
